### YamlMime:ManagedReference
items:
- uid: WSSInterfacing.StimParamsConfig
  commentId: T:WSSInterfacing.StimParamsConfig
  id: StimParamsConfig
  parent: WSSInterfacing
  children:
  - WSSInterfacing.StimParamsConfig.#ctor(System.String)
  langs:
  - csharp
  - vb
  name: StimParamsConfig
  nameWithType: StimParamsConfig
  fullName: WSSInterfacing.StimParamsConfig
  type: Class
  assemblies:
  - ApiProject
  namespace: WSSInterfacing
  summary: >-
    JSON-backed stimulation-parameters configuration. Inherits common JSON

    handling from <xref href="WSSInterfacing.DictConfigBase" data-throw-if-not-resolved="false"></xref> and seeds default per-channel

    values under the <code>stim.ch</code> hierarchy.
  example: []
  syntax:
    content: 'public sealed class StimParamsConfig : DictConfigBase'
    content.vb: Public NotInheritable Class StimParamsConfig Inherits DictConfigBase
  inheritance:
  - System.Object
  - WSSInterfacing.DictConfigBase
  inheritedMembers:
  - WSSInterfacing.DictConfigBase.Path
  - WSSInterfacing.DictConfigBase.Save
  - WSSInterfacing.DictConfigBase.TryGetFloat(System.String,System.Single@)
  - WSSInterfacing.DictConfigBase.TryGetInt(System.String,System.Int32@)
  - WSSInterfacing.DictConfigBase.TryGetString(System.String,System.String@)
  - WSSInterfacing.DictConfigBase.TryGetFloatArray(System.String,System.Single[]@)
  - WSSInterfacing.DictConfigBase.GetFloat(System.String,System.Single)
  - WSSInterfacing.DictConfigBase.GetInt(System.String,System.Int32)
  - WSSInterfacing.DictConfigBase.GetString(System.String,System.String)
  - WSSInterfacing.DictConfigBase.Set(System.String,Newtonsoft.Json.Linq.JToken)
- uid: WSSInterfacing.StimParamsConfig.#ctor(System.String)
  commentId: M:WSSInterfacing.StimParamsConfig.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: WSSInterfacing.StimParamsConfig
  langs:
  - csharp
  - vb
  name: StimParamsConfig(string)
  nameWithType: StimParamsConfig.StimParamsConfig(string)
  fullName: WSSInterfacing.StimParamsConfig.StimParamsConfig(string)
  type: Constructor
  assemblies:
  - ApiProject
  namespace: WSSInterfacing
  syntax:
    content: public StimParamsConfig(string path)
    parameters:
    - id: path
      type: System.String
    content.vb: Public Sub New(path As String)
  overload: WSSInterfacing.StimParamsConfig.#ctor*
  nameWithType.vb: StimParamsConfig.New(String)
  fullName.vb: WSSInterfacing.StimParamsConfig.New(String)
  name.vb: New(String)
references:
- uid: WSSInterfacing.DictConfigBase
  commentId: T:WSSInterfacing.DictConfigBase
  parent: WSSInterfacing
  href: WSSInterfacing.DictConfigBase.html
  name: DictConfigBase
  nameWithType: DictConfigBase
  fullName: WSSInterfacing.DictConfigBase
- uid: WSSInterfacing
  commentId: N:WSSInterfacing
  href: WSSInterfacing.html
  name: WSSInterfacing
  nameWithType: WSSInterfacing
  fullName: WSSInterfacing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: WSSInterfacing.DictConfigBase.Path
  commentId: P:WSSInterfacing.DictConfigBase.Path
  parent: WSSInterfacing.DictConfigBase
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Path
  name: Path
  nameWithType: DictConfigBase.Path
  fullName: WSSInterfacing.DictConfigBase.Path
- uid: WSSInterfacing.DictConfigBase.Save
  commentId: M:WSSInterfacing.DictConfigBase.Save
  parent: WSSInterfacing.DictConfigBase
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Save
  name: Save()
  nameWithType: DictConfigBase.Save()
  fullName: WSSInterfacing.DictConfigBase.Save()
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.Save
    name: Save
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Save
  - name: (
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.Save
    name: Save
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Save
  - name: (
  - name: )
- uid: WSSInterfacing.DictConfigBase.TryGetFloat(System.String,System.Single@)
  commentId: M:WSSInterfacing.DictConfigBase.TryGetFloat(System.String,System.Single@)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloat_System_String_System_Single__
  name: TryGetFloat(string, out float)
  nameWithType: DictConfigBase.TryGetFloat(string, out float)
  fullName: WSSInterfacing.DictConfigBase.TryGetFloat(string, out float)
  nameWithType.vb: DictConfigBase.TryGetFloat(String, Single)
  fullName.vb: WSSInterfacing.DictConfigBase.TryGetFloat(String, Single)
  name.vb: TryGetFloat(String, Single)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.TryGetFloat(System.String,System.Single@)
    name: TryGetFloat
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloat_System_String_System_Single__
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.TryGetFloat(System.String,System.Single@)
    name: TryGetFloat
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloat_System_String_System_Single__
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.TryGetInt(System.String,System.Int32@)
  commentId: M:WSSInterfacing.DictConfigBase.TryGetInt(System.String,System.Int32@)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetInt_System_String_System_Int32__
  name: TryGetInt(string, out int)
  nameWithType: DictConfigBase.TryGetInt(string, out int)
  fullName: WSSInterfacing.DictConfigBase.TryGetInt(string, out int)
  nameWithType.vb: DictConfigBase.TryGetInt(String, Integer)
  fullName.vb: WSSInterfacing.DictConfigBase.TryGetInt(String, Integer)
  name.vb: TryGetInt(String, Integer)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.TryGetInt(System.String,System.Int32@)
    name: TryGetInt
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetInt_System_String_System_Int32__
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.Int32
    name: int
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.TryGetInt(System.String,System.Int32@)
    name: TryGetInt
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetInt_System_String_System_Int32__
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.TryGetString(System.String,System.String@)
  commentId: M:WSSInterfacing.DictConfigBase.TryGetString(System.String,System.String@)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetString_System_String_System_String__
  name: TryGetString(string, out string)
  nameWithType: DictConfigBase.TryGetString(string, out string)
  fullName: WSSInterfacing.DictConfigBase.TryGetString(string, out string)
  nameWithType.vb: DictConfigBase.TryGetString(String, String)
  fullName.vb: WSSInterfacing.DictConfigBase.TryGetString(String, String)
  name.vb: TryGetString(String, String)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.TryGetString(System.String,System.String@)
    name: TryGetString
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetString_System_String_System_String__
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.TryGetString(System.String,System.String@)
    name: TryGetString
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetString_System_String_System_String__
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.TryGetFloatArray(System.String,System.Single[]@)
  commentId: M:WSSInterfacing.DictConfigBase.TryGetFloatArray(System.String,System.Single[]@)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloatArray_System_String_System_Single____
  name: TryGetFloatArray(string, out float[])
  nameWithType: DictConfigBase.TryGetFloatArray(string, out float[])
  fullName: WSSInterfacing.DictConfigBase.TryGetFloatArray(string, out float[])
  nameWithType.vb: DictConfigBase.TryGetFloatArray(String, Single())
  fullName.vb: WSSInterfacing.DictConfigBase.TryGetFloatArray(String, Single())
  name.vb: TryGetFloatArray(String, Single())
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.TryGetFloatArray(System.String,System.Single[]@)
    name: TryGetFloatArray
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloatArray_System_String_System_Single____
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.TryGetFloatArray(System.String,System.Single[]@)
    name: TryGetFloatArray
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_TryGetFloatArray_System_String_System_Single____
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
  - name: (
  - name: )
  - name: )
- uid: WSSInterfacing.DictConfigBase.GetFloat(System.String,System.Single)
  commentId: M:WSSInterfacing.DictConfigBase.GetFloat(System.String,System.Single)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetFloat_System_String_System_Single_
  name: GetFloat(string, float)
  nameWithType: DictConfigBase.GetFloat(string, float)
  fullName: WSSInterfacing.DictConfigBase.GetFloat(string, float)
  nameWithType.vb: DictConfigBase.GetFloat(String, Single)
  fullName.vb: WSSInterfacing.DictConfigBase.GetFloat(String, Single)
  name.vb: GetFloat(String, Single)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.GetFloat(System.String,System.Single)
    name: GetFloat
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetFloat_System_String_System_Single_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.GetFloat(System.String,System.Single)
    name: GetFloat
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetFloat_System_String_System_Single_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.GetInt(System.String,System.Int32)
  commentId: M:WSSInterfacing.DictConfigBase.GetInt(System.String,System.Int32)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetInt_System_String_System_Int32_
  name: GetInt(string, int)
  nameWithType: DictConfigBase.GetInt(string, int)
  fullName: WSSInterfacing.DictConfigBase.GetInt(string, int)
  nameWithType.vb: DictConfigBase.GetInt(String, Integer)
  fullName.vb: WSSInterfacing.DictConfigBase.GetInt(String, Integer)
  name.vb: GetInt(String, Integer)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.GetInt(System.String,System.Int32)
    name: GetInt
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetInt_System_String_System_Int32_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Int32
    name: int
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.GetInt(System.String,System.Int32)
    name: GetInt
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetInt_System_String_System_Int32_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.GetString(System.String,System.String)
  commentId: M:WSSInterfacing.DictConfigBase.GetString(System.String,System.String)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetString_System_String_System_String_
  name: GetString(string, string)
  nameWithType: DictConfigBase.GetString(string, string)
  fullName: WSSInterfacing.DictConfigBase.GetString(string, string)
  nameWithType.vb: DictConfigBase.GetString(String, String)
  fullName.vb: WSSInterfacing.DictConfigBase.GetString(String, String)
  name.vb: GetString(String, String)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.GetString(System.String,System.String)
    name: GetString
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetString_System_String_System_String_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.GetString(System.String,System.String)
    name: GetString
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_GetString_System_String_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
  - name: )
- uid: WSSInterfacing.DictConfigBase.Set(System.String,Newtonsoft.Json.Linq.JToken)
  commentId: M:WSSInterfacing.DictConfigBase.Set(System.String,Newtonsoft.Json.Linq.JToken)
  parent: WSSInterfacing.DictConfigBase
  isExternal: true
  href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Set_System_String_Newtonsoft_Json_Linq_JToken_
  name: Set(string, JToken)
  nameWithType: DictConfigBase.Set(string, JToken)
  fullName: WSSInterfacing.DictConfigBase.Set(string, Newtonsoft.Json.Linq.JToken)
  nameWithType.vb: DictConfigBase.Set(String, JToken)
  fullName.vb: WSSInterfacing.DictConfigBase.Set(String, Newtonsoft.Json.Linq.JToken)
  name.vb: Set(String, JToken)
  spec.csharp:
  - uid: WSSInterfacing.DictConfigBase.Set(System.String,Newtonsoft.Json.Linq.JToken)
    name: Set
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Set_System_String_Newtonsoft_Json_Linq_JToken_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
  - name: ','
  - name: " "
  - uid: Newtonsoft.Json.Linq.JToken
    name: JToken
    isExternal: true
  - name: )
  spec.vb:
  - uid: WSSInterfacing.DictConfigBase.Set(System.String,Newtonsoft.Json.Linq.JToken)
    name: Set
    href: WSSInterfacing.DictConfigBase.html#WSSInterfacing_DictConfigBase_Set_System_String_Newtonsoft_Json_Linq_JToken_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
  - name: ','
  - name: " "
  - uid: Newtonsoft.Json.Linq.JToken
    name: JToken
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: WSSInterfacing.StimParamsConfig.#ctor*
  commentId: Overload:WSSInterfacing.StimParamsConfig.#ctor
  href: WSSInterfacing.StimParamsConfig.html#WSSInterfacing_StimParamsConfig__ctor_System_String_
  name: StimParamsConfig
  nameWithType: StimParamsConfig.StimParamsConfig
  fullName: WSSInterfacing.StimParamsConfig.StimParamsConfig
  nameWithType.vb: StimParamsConfig.New
  fullName.vb: WSSInterfacing.StimParamsConfig.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
